spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: shopping-microservice
          uri: lb://shopping-microservice
          predicates:
            - Path=/shopping/**
        - id: inventory-microservice
          uri: lb://inventory-microservice
          predicates:
            - Path=/inventory/**