spring:
  application:
    name: inventory-microservice
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/univiser_ms_demo_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password: ""

